void convert_lower(char str[]);
int convert_index(char str[]);
void add_song(char n[], char a[]);
struct song_node *search_song(char n[], char a[]);
struct song_node *search_artist(char a[]);
struct song_node *search_artist_r(char a[], struct song_node *start);
void print_lib_letter(char a);
void print_artist(char a[]);
void print_library();
void print_shuffle(int count);
void delete_song(char n[], char a[]);
void delete_library();
